### ISSUE TITLE
class DuiXmlDocument : public DuiXmlNode 继承错误

### ISSUE THREAD

**Issue by soarnic** [blueantst/DuiVision#36]
class DuiXmlDocument : public DuiXmlNode 继承错误
\DuiVision\include\DuiXml.h中 77 行
应改为class DuiXmlDocument : public xml_document /_DuiXmlNode [2016.06.05][MODIFY]_/
1. 编译不会产生错误。
2. 可以使用m_document.save_file(contents);

**Comment by blueantst** [comment]
谢谢，已经修改提交了。
