### ISSUE TITLE
Demo中的基础控件点击其它会异常，且DuiVision-master中的部分demo不是最新的，建议刷新。

### ISSUE THREAD

**Issue by angelyouyou** [blueantst/DuiVision#49]
![image](https://cloud.githubusercontent.com/assets/12936259/20470976/6df474f8-afe8-11e6-98d1-436fe2fbb1f0.png)

**Comment by blueantst** [comment]
没有出现这个问题，更新到最新代码试一下

**Comment by angelyouyou** [comment]
-		rcSrc	{top=0x000001ae bottom=0x000001d6 left=0x00000034 right=0x0000012e}	const CRect &
-		tagRECT	{top=0x000001ae bottom=0x000001d6 left=0x00000034 right=0x0000012e}	tagRECT
		left	0x00000034	long
		top	0x000001ae	long
		right	0x0000012e	long
		bottom	0x000001d6	long
-		rcDes	{top=0x00000001 bottom=0x00000028 left=0x00000001 right=0x000000fa}	const CRect &
-		tagRECT	{top=0x00000001 bottom=0x00000028 left=0x00000001 right=0x000000fa}	tagRECT
		left	0x00000001	long
		top	0x00000001	long
		right	0x000000fa	long
		bottom	0x00000028	long

**Comment by angelyouyou** [comment]
![Uploading image.png…]()

**Comment by angelyouyou** [comment]
if(m_nTransparentType == TRANSPARENT_HORIZONTAL)
		{
			DrawHorizontalTransition(m_memDC, dc, CRect(m_nFrameWidth, m_nFrameWidth, nWidth, nHeight),	// 水平背景透明度
				m_rc, m_nBeginTransparent, m_nEndTransparent);
		}


 	DuiVisionDemo.2013d.exe!DrawHorizontalTransition(CDC & dcDes, CDC & dcSrc, const CRect & rcDes, const CRect & rcSrc, int nBeginTransparent, int nEndTransparent) 行 636	C++
>	DuiVisionDemo.2013d.exe!CRectangle::DrawControl(CDC & dc, CRect rcUpdate) 行 63	C++
 	DuiVisionDemo.2013d.exe!CControlBase::Draw(CDC & dc, CRect rcUpdate) 行 185	C++
 	DuiVisionDemo.2013d.exe!CControlBase::DrawSubControls(CDC & dc, CRect rcUpdate) 行 212	C++
 	DuiVisionDemo.2013d.exe!CDuiPanel::DrawSubControls(CDC & dc, CRect rcUpdate) 行 468	C++
 	DuiVisionDemo.2013d.exe!CControlBase::Draw(CDC & dc, CRect rcUpdate) 行 198	C++
 	DuiVisionDemo.2013d.exe!CDuiTabCtrl::DrawSubControls(CDC & dc, CRect rcUpdate) 行 2051	C++
 	DuiVisionDemo.2013d.exe!CControlBase::Draw(CDC & dc, CRect rcUpdate) 行 198	C++
 	DuiVisionDemo.2013d.exe!CControlBase::DrawSubControls(CDC & dc, CRect rcUpdate) 行 212	C++
 	DuiVisionDemo.2013d.exe!CDuiPanel::DrawSubControls(CDC & dc, CRect rcUpdate) 行 468	C++
 	DuiVisionDemo.2013d.exe!CControlBase::Draw(CDC & dc, CRect rcUpdate) 行 198	C++
 	DuiVisionDemo.2013d.exe!CControlBase::DrawSubControls(CDC & dc, CRect rcUpdate) 行 212	C++
 	DuiVisionDemo.2013d.exe!CDuiTabCtrl::DrawSubControls(CDC & dc, CRect rcUpdate) 行 1976	C++
 	DuiVisionDemo.2013d.exe!CControlBase::Draw(CDC & dc, CRect rcUpdate) 行 198	C++
 	DuiVisionDemo.2013d.exe!CDlgBase::DrawControl(CDC & dc, const CRect & rcUpdate) 行 1408	C++
 	DuiVisionDemo.2013d.exe!CDlgBase::DrawBackgroundAndControls(CDC & dc, const CRect & rcClient, const CRect & rcUpdate) 行 1258	C++
 	DuiVisionDemo.2013d.exe!CDlgBase::OnPaint() 行 1232	C++

**Comment by blueantst** [comment]
已修改，将DrawHorizontalTransition函数中的ASSERT注释掉了。
