### ISSUE TITLE
建议duivision支持ip地址控件和日期控件

### ISSUE THREAD

**Issue by angelyouyou** [blueantst/DuiVision#50]
如题

**Comment by blueantst** [comment]
日期控件已经有了，是网友简单人生提供的，因为是基于MFC实现的，没有合并到DuiVision库代码中，而是作为自定义控件放在demo程序中了，使用的话可以参考demo程序的用法，把demo程序中DuiControlEx目录下的MFCDateTime.h和MFCDateTime.cpp代码添加到自己的代码中，在程序启动的时候用下面的代码注册一下，就可以使用了。
```C++
// 注册MFCDateTime控件
	REGISTER_DUICONTROL(CMFCDateTime, NULL);
```
xml的定义可以参考demo程序的编辑框页面的演示，xml中的控件名为mfcdatetime，属性value设置为now表示初始显示当前时间，属性datetime可以指定一个初始显示时间。

IP地址控件目前没有，可以参考日期控件的实现方式自己实现一个自定义控件，IP地址控件也可以在目前的edit控件基础上实现，主要是要把编辑状态的原生控件修改为一个支持IP地址格式的控件，可以参考一些MFC的IP地址控件的实现方式。
